### ISSUE TITLE
Add to the slides more info

### ISSUE THREAD

**Issue by vladimirkovacevic** [nada-jovanovic/genome-informatics-etf#2]
1. Explain the most relevant gene selection process
2. In the diagrams, how many samples were present in the training and cross-validation? How did you perform division?
3. Explain the process of selecting the best hyperparameters for Lasso
4. Does the model overfit?

**Comment by nada-jovanovic** [comment]
@vladimirkovacevic Thank you for the feedback. 

I'll update the presentation with the things you suggested and post a link in the comments. 

Some info that is missing from the slides is either printed out in the notebook (shape of the training samples used in cross-validation for example) or is explained in more details in the markdown part of the notebook.

**Comment by nada-jovanovic** [comment]
Hey @vladimirkovacevic here is the [link](
https://docs.google.com/presentation/d/17cDBME43oQdNNeyTjc9Va8J5w_TTcwfk5SW8LRg8IZA/edit?usp=sharing) for the updated presentation. 
As you suggested, I added more info on gene selection process & overall evaluation process.

Hope this seems ok now.

**Comment by vladimirkovacevic** [comment]
Thx
